### ISSUE TITLE
where do these poses come from？./demo_data/pose_img/0049.png","./demo_data/pose_img/0198.png","./demo_data/pose_img/0213.png"

### ISSUE THREAD

**Issue by zhangtao22** [Wangt-CN/DisCo#16]
"./demo_data/pose_img/0049.png","./demo_data/pose_img/0198.png","./demo_data/pose_img/0213.png","./demo_data/pose_img/0264.png","./demo_data/pose_img/0144.png","./demo_data/pose_img/0054.png"
obviously， these are part of poses. How can I get the entire poses dataset.
In addition, there are dance1-5. How can I get these poses dataset？Thx

**Comment by Wangt-CN** [comment]
The pose image in demo is just the separate for running the demo. You can use any video you want. But note that current model is fine-tuning on the TikTok data, therefore prefer the Tiktok-style image/pose. Due to the original resolution issue of SD, if you use a human image with a small size human, the human face generation will become worse. Thx.
