### ISSUE TITLE
Incorrect parameter name in config scripts

### ISSUE THREAD

**Issue by emcorby2** [Wangt-CN/DisCo#22]
When running the Gradio Demo, this error kept generating when it was loading the pre-trained unet: **`TypeError: get_down_block() got an unexpected keyword argument 'attn_num_head_channels'`**

Looking at how the other parameters were named, I tried changing it to 'attention_head_dim', however that then created this error: **`TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'`**

Once I expanded the error and viewed it in full, I noticed `num_attention_heads` was mentioned yet this was not present in any of the scripts. Therefore, I tried changing the parameter name to this and the code ran successfully.

**Hence, all instances of `attn_num_head_channels` in the following scripts need to be changed to `num_attention_heads`:**

- _controlnet_main.py_
- _controlnet.py_
- _unet_2d_condition.py_

**Comment by Wangt-CN** [comment]
Hi @emcorby2 , sorry for the late reply due to my vacation leave. Thanks for your comments!
From your error message, It seemed that the demo code cannot run without revising the `attn_num_head_channels`. I do not meet this error when building the demo file actually. So I wonder where comes this problem. May I double-check your version of the installed package?

**Comment by suzhaoqi** [comment]
> `num_attention_heads`

Hi, thank you for your information! 
I wonder if I should also add `attention_head_dim=attention_head_dim[i]` besides the `num_attention_heads=attention_head_dim[i]` in `get_down_block`, because there is a "It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8." message?

**Comment by robbinhan** [comment]
I reinstall `diffusers[torch]==0.14.0` fixed this issue

**Comment by emcorby2** [comment]
@robbinhan Just tried this and worked for me too! It also solved some issues I had with module names imported from the diffusers/model folder. Thank you!

**Comment by Wangt-CN** [comment]
Happy that you have figured it out.
