### ISSUE TITLE
About the training data

### ISSUE THREAD

**Issue by XiaoqiangZhou** [Wangt-CN/DisCo#26]
Thanks for sharing this great work!

I find that you uploaded the training data to the google cloud in tsv format. It is inconvenient for me to download the data with google cloud. Could you please upload a copy of the data to other cloud storage, such as google drive, aliyun, or baiduyun? 

Thanks

**Comment by Wangt-CN** [comment]
Hi @XiaoqiangZhou , I have submitted the query to the corporation to open-source the additional TikTok-style data. Since it is collected by the corporation so we need to get the permission.
Currently, if you want to make a fair comparison, you could follow the penultimate line of Table 1 which does not use the additional data for training.

**Comment by Wangt-CN** [comment]
Hi @XiaoqiangZhou , sure, I will try to upload a copy to another cloud storage.
