### ISSUE TITLE
How can it be successfully run inference on multiple GPUs? 

### ISSUE THREAD

**Issue by Yongssss** [Wangt-CN/DisCo#42]
Whichever port I use for multiple-GPU inference, I always get the error that is the address already in use.

For example, I set "export MASTER_PORT=65530" before inference on multiple GPUs and then I will get an error as follows:
 
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:65530 (errno: 98 - Address already in use). The server socket has failed to bind to?UNKNOWN? (errno: 98 - Address already in use).

**Comment by Wangt-CN** [comment]
Hi @Yongssss, sorry for the late reply due to my very limited bandwidth recently. This error indicates that there is another program using the same port. A simple work around is to change the master port in `utils/dist.py`. But you may need to first check if using the correct multiple-GPU inference code: mpirun -np 8 [readme here](https://github.com/Wangt-CN/DisCo#2-wo-classifier-free-guidance-cfg)?
